name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  laravel:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      APP_KEY: base64:placeholderKey=
      DB_CONNECTION: sqlite
      DB_DATABASE: ':memory:'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_pgsql, pgsql, xml
          coverage: none

      - name: Install Composer dependencies
        working-directory: backend
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Copy .env
        working-directory: backend
        run: cp .env.example .env

      - name: Generate app key
        working-directory: backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: backend
        run: php artisan migrate --seed

      - name: Run tests (PHPUnit)
        working-directory: backend
        run: php artisan test

  deploy:
    name: Deploy to Railway / Render
    runs-on: ubuntu-latest
    needs: laravel
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Railway (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}

      - name: Deploy to Render (Staging)
        if: github.ref == 'refs/heads/develop'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
